export const comicsData = [
  {
    id: '001',
    title: 'The Dark Multiverse',
    publisher: 'DC',
    character: 'Batman',
    genre: 'Superhero',
    price: 415,
    releaseDate: '2025-01-15',
    coverImage: '/dark-batman-comic-book-cover-noir-gothic.jpg',
    description: 'Batman faces his greatest challenge yet as the Dark Multiverse threatens to consume everything. A mind-bending adventure that will leave you questioning reality itself.',
    creators: ['Scott Snyder', 'Greg Capullo'],
    featured: true
  },
  {
    id: '002',
    title: 'Web of Destiny',
    publisher: 'Marvel',
    character: 'Spider-Man',
    genre: 'Superhero',
    price: 330,
    releaseDate: '2025-01-20',
    coverImage: '/spiderman-swinging-through-new-york-city-comic-cov.jpg',
    description: 'Spider-Man swings into action when a new villain threatens New York. Experience the thrill of web-slinging through the city in this action-packed issue!',
    creators: ['Zeb Wells', 'John Romita Jr.'],
    featured: true
  },
  {
    id: '003',
    title: 'Wonder Chronicles',
    publisher: 'DC',
    character: 'Wonder Woman',
    genre: 'Superhero',
    price: 415,
    releaseDate: '2025-02-01',
    coverImage: '/wonder-woman-warrior-goddess-comic-cover.jpg',
    description: 'Diana Prince returns to Themyscira to face an ancient threat. A tale of gods, warriors, and the power of truth in a world of deception.',
    creators: ['Tom King', 'Daniel Sampere'],
    featured: false
  },
  {
    id: '004',
    title: 'Iron Legion',
    publisher: 'Marvel',
    character: 'Iron Man',
    genre: 'Superhero',
    price: 375,
    releaseDate: '2025-02-05',
    coverImage: '/iron-man-high-tech-armor-flying-comic-cover.jpg',
    description: 'Tony Stark unveils his most advanced armor yet, but will it be enough to stop the new tech-based villain? High-tech action meets human drama.',
    creators: ['Christopher Cantwell', 'CAFU'],
    featured: true
  },
  {
    id: '005',
    title: 'Cosmic Guardians',
    publisher: 'Marvel',
    character: 'Guardians',
    genre: 'Sci-Fi',
    price: 330,
    releaseDate: '2025-02-10',
    coverImage: '/guardians-of-galaxy-space-adventure-comic-cover.jpg',
    description: 'The Guardians of the Galaxy face a cosmic threat that could destroy entire galaxies. A wild space adventure filled with humor and heart.',
    creators: ['Al Ewing', 'Juan Frigeri'],
    featured: false
  },
  {
    id: '006',
    title: 'Savage Saga',
    publisher: 'Image',
    character: 'Spawn',
    genre: 'Horror',
    price: 250,
    releaseDate: '2025-02-15',
    coverImage: '/spawn-dark-hellish-chains-comic-cover.jpg',
    description: 'Spawn descends into the depths of hell to confront his past. A dark, visceral journey that redefines the character for a new generation.',
    creators: ['Todd McFarlane', 'Greg Capullo'],
    featured: false
  },
  {
    id: '007',
    title: 'Flash Forward',
    publisher: 'DC',
    character: 'Flash',
    genre: 'Superhero',
    price: 330,
    releaseDate: '2025-02-20',
    coverImage: '/flash-lightning-speed-running-comic-cover.jpg',
    description: 'Barry Allen races through time to prevent a catastrophic future. Speed, science, and sacrifice collide in this thrilling tale.',
    creators: ['Joshua Williamson', 'Howard Porter'],
    featured: false
  },
  {
    id: '008',
    title: 'Mutant Revolution',
    publisher: 'Marvel',
    character: 'X-Men',
    genre: 'Superhero',
    price: 415,
    releaseDate: '2025-03-01',
    coverImage: '/xmen-mutants-team-action-comic-cover.jpg',
    description: 'The X-Men face their greatest test as mutant-kind stands at a crossroads. A revolutionary story about identity, acceptance, and power.',
    creators: ['Jonathan Hickman', 'Pepe Larraz'],
    featured: true
  },
  {
    id: '009',
    title: 'Walking Dead: Aftermath',
    publisher: 'Image',
    character: 'Original',
    genre: 'Horror',
    price: 290,
    releaseDate: '2025-03-05',
    coverImage: '/zombie-apocalypse-survivors-comic-cover.jpg',
    description: 'Survivors navigate a post-apocalyptic world where the real monsters might be human. A gripping tale of survival and humanity.',
    creators: ['Robert Kirkman', 'Charlie Adlard'],
    featured: false
  },
  {
    id: '010',
    title: 'Saga of Stars',
    publisher: 'Image',
    character: 'Original',
    genre: 'Sci-Fi',
    price: 250,
    releaseDate: '2025-03-10',
    coverImage: '/epic-space-family-saga-colorful-comic-cover.jpg',
    description: 'An epic space opera about love, family, and war. Beautiful art combines with powerful storytelling in this modern masterpiece.',
    creators: ['Brian K. Vaughan', 'Fiona Staples'],
    featured: false
  },
  {
    id: '011',
    title: 'Harley\'s Havoc',
    publisher: 'DC',
    character: 'Harley Quinn',
    genre: 'Action',
    price: 330,
    releaseDate: '2025-03-15',
    coverImage: '/harley-quinn-chaos-colorful-mallet-comic-cover.jpg',
    description: 'Harley Quinn causes chaos across Gotham in the most entertaining way possible. Colorful, chaotic, and completely unpredictable!',
    creators: ['Stephanie Phillips', 'Riley Rossmo'],
    featured: false
  },
  {
    id: '012',
    title: 'Thor: Thunder God',
    publisher: 'Marvel',
    character: 'Thor',
    genre: 'Fantasy',
    price: 375,
    releaseDate: '2025-03-20',
    coverImage: '/thor-mjolnir-hammer-lightning-asgard-comic-cover.jpg',
    description: 'The God of Thunder faces a threat from beyond the Nine Realms. Epic battles and Norse mythology collide in spectacular fashion.',
    creators: ['Donny Cates', 'Nic Klein'],
    featured: false
  },
  {
    id: '013',
    title: 'Black Panther: Wakanda Forever',
    publisher: 'Marvel',
    character: 'Black Panther',
    genre: 'Superhero',
    price: 415,
    releaseDate: '2025-03-25',
    coverImage: '/black-panther-wakanda-tech-african-comic-cover.jpg',
    description: 'T\'Challa must defend Wakanda from a technological invasion that threatens to expose its secrets. A thrilling blend of tradition and innovation.',
    creators: ['Ta-Nehisi Coates', 'Brian Stelfreeze'],
    featured: true
  },
  {
    id: '014',
    title: 'Joker: Madness',
    publisher: 'DC',
    character: 'Joker',
    genre: 'Thriller',
    price: 500,
    releaseDate: '2025-04-01',
    coverImage: '/joker-insane-smile-dark-gotham-comic-cover.jpg',
    description: 'The Clown Prince of Crime orchestrates his most elaborate scheme yet. A psychological thriller that explores the nature of madness itself.',
    creators: ['Geoff Johns', 'Jason Fabok'],
    featured: false
  },
  {
    id: '015',
    title: 'Avengers: Endgame',
    publisher: 'Marvel',
    character: 'Avengers',
    genre: 'Superhero',
    price: 455,
    releaseDate: '2025-04-05',
    coverImage: '/avengers-team-assemble-epic-battle-comic-cover.jpg',
    description: 'Earth\'s Mightiest Heroes face their ultimate challenge. An epic crossover event that will change the Marvel Universe forever.',
    creators: ['Jason Aaron', 'Ed McGuinness'],
    featured: true
  },
  {
    id: '016',
    title: 'Invincible Returns',
    publisher: 'Image',
    character: 'Invincible',
    genre: 'Superhero',
    price: 330,
    releaseDate: '2025-04-10',
    coverImage: '/invincible-superhero-flying-action-comic-cover.jpg',
    description: 'Mark Grayson returns to face a threat from his past. A fresh take on superhero comics with brutal honesty and emotional depth.',
    creators: ['Robert Kirkman', 'Ryan Ottley'],
    featured: false
  },
  {
    id: '017',
    title: 'Aquaman: Deep Rising',
    publisher: 'DC',
    character: 'Aquaman',
    genre: 'Adventure',
    price: 355,
    releaseDate: '2025-04-15',
    coverImage: '/aquaman-underwater-trident-ocean-comic-cover.jpg',
    description: 'Arthur Curry discovers an ancient underwater civilization with dark secrets. Dive into an epic aquatic adventure unlike any other.',
    creators: ['Kelly Sue DeConnick', 'Robson Rocha'],
    featured: false
  },
  {
    id: '018',
    title: 'Doctor Strange: Mystic Arts',
    publisher: 'Marvel',
    character: 'Doctor Strange',
    genre: 'Fantasy',
    price: 395,
    releaseDate: '2025-04-20',
    coverImage: '/doctor-strange-magic-mystic-arts-comic-cover.jpg',
    description: 'The Sorcerer Supreme battles threats from across multiple dimensions. Mind-bending visuals and magical mayhem await.',
    creators: ['Jed MacKay', 'Pasqual Ferry'],
    featured: true
  },
  {
    id: '019',
    title: 'Teen Titans: New Generation',
    publisher: 'DC',
    character: 'Teen Titans',
    genre: 'Superhero',
    price: 310,
    releaseDate: '2025-04-25',
    coverImage: '/teen-titans-young-heroes-team-comic-cover.jpg',
    description: 'A new generation of heroes rises to protect the world. Youthful energy meets heroic responsibility in this coming-of-age story.',
    creators: ['Tom Taylor', 'Bruno Redondo'],
    featured: false
  },
  {
    id: '020',
    title: 'Deadpool: Maximum Effort',
    publisher: 'Marvel',
    character: 'Deadpool',
    genre: 'Action',
    price: 330,
    releaseDate: '2025-05-01',
    coverImage: '/deadpool-mercenary-action-comedy-comic-cover.jpg',
    description: 'Wade Wilson breaks the fourth wall while breaking bad guys. Hilarious, violent, and unexpectedly heartfelt - classic Deadpool!',
    creators: ['Gerry Duggan', 'Mike Hawthorne'],
    featured: false
  }
];
